app:
  env: local
  port: 8080
  app_name: gin-skill
  app_url: http://localhost

log:
  level: debug
  dir: ./storage/logs
  filename: app.log
  format: json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 1 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: test
  username: root
  password: 123456
  charset: utf8mb4
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info
  enable_file_log_writer: false # 是否启用日志文件
  log_filename: sql.log

jwt:
  secret: 3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s
  expire: 3600