app:
  env: local
  port: 8080
  app_name: gin-skill
  app_url: http://localhost

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  database: test
  username: root
  password: 123456
  charset: utf8mb4
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log

