// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/shopspring/decimal"
	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID        int64           `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64           `gorm:"column:user_id;type:int unsigned;not null;comment:用户id" json:"user_id"`                      // 用户id
	CreatedAt time.Time       `gorm:"column:created_at;type:timestamp;not null;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt time.Time       `gorm:"column:updated_at;type:timestamp;not null;comment:更新时间" json:"updated_at"`                   // 更新时间
	DeletedAt gorm.DeletedAt  `gorm:"column:deleted_at;type:timestamp;comment:删除时间" json:"deleted_at"`                            // 删除时间
	Name      string          `gorm:"column:name;type:varchar(10);not null;comment:名称" json:"name"`                               // 名称
	Longitude decimal.Decimal `gorm:"column:longitude;type:decimal(10,7);not null;default:0.0000000;comment:经度" json:"longitude"` // 经度
	Latitude  decimal.Decimal `gorm:"column:latitude;type:decimal(10,7);not null;default:0.0000000;comment:纬度" json:"latitude"`   // 纬度
	Address   string          `gorm:"column:address;type:varchar(100);not null;comment:地址" json:"address"`                        // 地址
	Province  string          `gorm:"column:province;type:varchar(50);not null;comment:省" json:"province"`                        // 省
	City      string          `gorm:"column:city;type:varchar(50);not null;comment:市" json:"city"`                                // 市
	District  string          `gorm:"column:district;type:varchar(50);not null;comment:区" json:"district"`                        // 区
	User      User            `gorm:"foreignKey:UserID;references:ID" json:"user"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
